# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
- stage: build
  jobs:
  - job: job1
    steps:
    - script: echo "hello world"
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'echo "script2 in job1"'
  - job: job2
    steps:
    - script: echo "hello world from job2"
    - script: echo "hello world from step2, job 2"


  
